## Numpy array and basics

In [2]:
import numpy as np

### Creating array from list

In [5]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List va numpy array

In [7]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list * 2)



np_array = np.array([1, 2, 3]) # element wise multiplication
print("numpy array multiplication: ", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n numpy operation time: ", time.time() - start)



Python list multiplication:  [1, 2, 3, 1, 2, 3]
numpy array multiplication:  [2 4 6]

 List operation time:  0.12336397171020508

 numpy operation time:  0.007517337799072266


### Creating array from scratch

In [35]:
zeros = np.zeros((3, 4)) # 3 row 4 column
print("zeros array: \n", zeros)

ones = np.ones((2, 3)) # 2 row 3 column
print("One array: \n", ones)

full = np.full((2, 2), 7) # 2 row 2 column
print("Full array: \n", full)

random = np.random.random([2, 3])
print("random array: \n", random)

sequence = np.arange(0, 10, 2) # start, stop, step
print("Sequence array: ", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.60955888 0.47196306 0.0969104 ]
 [0.29136529 0.29341863 0.56489724]]
Sequence array:  [0 2 4 6 8]


### Vector, Matices and Tensor

In [36]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrices: ", matrix)

tensor = np.array([[[1, 2,], [3, 4]],
                   [[5, 6], [7, 8]]]) # in tensor, there is more dimension
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrices:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print("Array: ", arr)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Datatype: ", arr.dtype)

Array:  [['1' '2' '3']
 ['4' '5' 'true']]
Shape:  (2, 3)
Dimension:  2
Size:  6
Datatype:  <U21


### Array Reshaping

In [48]:
arr = np.arange(12) # n-1 means 12-1 = 11
print("Original array: ", arr)

reshaped = arr.reshape((3, 4)) # 3 row 4 column
print("Reshape array: ", reshaped)

flattened = reshaped.flatten() #returns copy
print("\n Flat: ", flattened)
# return view instead of copy
raveled = reshaped.ravel() #returns original array
print("\n raveled array: ", raveled)

# transpose
transpose = reshaped.T
print("\n Transposed array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flat:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
